language: node_js
node_js:
- node
addons:
  apt:
    packages:
    - nodejs-legacy
install:
- npm install -g gulp
- npm install -g typescript
- npm install
script:
- npm run test
- npm run lint
after_success:
- cat ./dist/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: contact@alexandereerenberg.nl
  on:
    branch: master
  api_key:
    secure: Ke3FAfX9NXVCju1ltZbAhbiP8XAdW3AL2bCdNZIlO89Swh5RROANC1gx8XfESMJtdl4uEx45qM8dUGil6E7ihVYtjU3yuNgeGeDrmnArmbIwnSxw6/zY5ca2Xy1Ptuja6FPrKiKaDkzX1SRD5jlhJ8+mtBOCjNo+Z/WAJTrWzZkqZeNuBi8Ch+61tche+xXmJ+iyzxyHJeCa1KV9K40xLrR4C4WVQEFWEf6I13im6qidf+BROx3/N3s78409qzBhTVxfZp1Db6aRnfmHUqgVdKZs7u9e5O3iYArP2Fh/HMLTa4pRyR40es71WxO6EFWvqO/RpWFsBpQbQOLOAazvFHG2Izi9LQowZbMhhsWnvYyWp2eQPgZOqBbfafWdm5mYLGfSKZfGdsZ4/GAqPqoVMrPkdSmgajh0wiI09MUhaZ4K+S47YgSY0h/LuZSC/yeX8yTRuWQ5Rk4FgFD4Q7Pb4JBCT65/phawPQPQWaYAIZmDKDw+4zzPLtNu1pbVi2Cm9sYe+lR5oi/JIOZhaF1KpLud2OPJXwVTONtfcBGXSfKWjJBuRGyMN4QcMz6x6NaIxZfMf+VTB2tRw0mbdSgEX/Ggm979j0ZXXUsmWtjJs8VMtx9goYGoriABDE+16Z2rtpSB50ZuMa2LPP5XRtOa1nGYNOGD9GQiHd2LmVglwek=