language: node_js
node_js:
- node
addons:
  apt:
    packages:
    - nodejs-legacy
install:
- npm install -g gulp
- npm install -g typescript
- npm install
script:
- npm run test
- npm run lint
after_success:
- cat ./dist/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: willem_liu@hotmail.com
  on:
    branch: master
  api_key:
    secure: Si3JGydUrSsYaDV3+G6mTZ748UGVifAW8LczZqo/cG6koiJQf6FdlObMe1O2f5EH9xqRJNCUOf4Fw2K0n+OayCov0rCEgUaQpew6WQTWljQ22thqiu5pb82PqyD5+OAbPBbZDBghrsy19qqN0x0irD9xOXdVFiCgrxl9gn6cn1K98eUzrG/ffa/q7b8NeqfwGIHWLhbLNHYVBn3QUa99PP7tSBYzOpOvgALIKymjeeVP68V30suNAcG3OcQFQENK9IvJoSbZY9j7U9eTiiwrnvIEH9OluD/qmYAxtudvw1JqMHqf3rhWc0CCaoiTRFD+ym/GlYIibxx0vCWBrXZZ51XKlwHjpitSDEGMUSBm31Gppl3OJybYbZTIFRiXIPAZKPrysnU0uxeQjRiOWUXii+2tMvr4/ekb+gK1tunrlS9vrIwntyyQlaMFK9c+4pKZ2ADWz9tT2s6aWAGb252vcorzL1cqjnCF4PpN76tob37K4wtXid4s5tAPXYPWY38JUCj4QGDGkNTMCs/GIiQ+5OF7H40J0s09AwUQcFDtAD/YaqpWbnO0jyJoNlldRSDsgZZSegiHSF3+KlNc3OtaQTRTAo9WejTPDq+rcFXzT+g/0yCeEafAS7Wvx27+JUAvyWTp1TSJNWLLaU44zms8H6QTNSRUImBu27fCCeOXmEg=
