language: node_js
node_js:
- node
addons:
  apt:
    packages:
    - nodejs-legacy
install:
- npm install -g gulp
- npm install -g typescript
- npm install
script:
- npm run test
- npm run lint
after_success:
- cat ./dist/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: contact@alexandereerenberg.nl
  on:
    branch: master
  api_key:
    secure: juDT3S+CQ3pB4IUHpphttoccwBxSXGxoyEDJyhdJovaK8zd/Hx/zE+QPhk+mWJSUReKxrshHNszhpT9Ffo+THiG/YcSqESKZB0cFAwPb1AcqSKqJIinR6JHOB2Wc4t3C4OLdyg0ZoZKTIQkewFwODasy8C9oJe7ub2eZpza8NLWKgAjwgjXfwFs9AxOZd0b5Mf+CZwQwCIMW3b8Sy+fS29xzS++dPH2v90WLZketvxCoKHu0iQ3esYBaBQaDaAum3ZAxnyEKQtjnP8Sdc1Oy4pljjDm4Zm4KvixlZs/90eUwojFE1aP1PASBWgwOqNVxCpGO8rO3+EbE7GGK9QccYm1cq0n1OjKt5tWJXYOZ5JQPzkwL84c9s91hxUwtWIdZbSBiuPuNC8Yj7+YUgxJUD15PT5jOVM7jBWRIzUfRSZOfNVwOgR3aHt62Lg+Df/55aSAc73oLnMvZXcn1JEsUO0/r2AHgsvfhuechotpWFrhKVkCzz1QbB1Dky5qbfG12uaLUAp1edmtSI7IW2++dXLWiIg6oaJMuWSutn3+/QCoJ/NQACIB/nwMefuExfQWClbJiwD6kcJSQp/MtoxsP8QtAM3IRL4Ua/eKqLK+QdrT5I4rlzqwkVb+aVRZ+5GJddyKMn5p1B4O6FFwhmCWlxVf6mocXf7NIW/V52bF0AFs=
